### PR TITLE
Changes for Dockerfile generation

### PR DESCRIPTION
**Pull request by raulsoledispa**
please your help with the revision of the changes made for the generation of Dockerfile

### CODE REVIEW

**Comment by BRAVO68WEB** [comment]
Awesome work, this is what is Just Wanted,

Thanks a lot

**Comment by raulsoledispa** [comment]
I would like to continue contributing to the project, do not hesitate to contact me to continue improving the project

**Comment by BRAVO68WEB** [comment]
sure

**Comment by BRAVO68WEB** [comment]
@all-contributors please add @raulsoledispa for code , doc

**Pull request merged**
