### PR TITLE
Add ruby support

### LINKED ISSUE #22: Add Ruby Support
**What's to be Done?**

* Add ``Ruby`` Language 
* Add Dependence installation support

### PR DESCRIPTION
**Pull request by Hyftar**
Hi I added support for Ruby / Rails / Sinatra and I made the code slightly more readable.

This PR closes #22

### CODE REVIEW

**Comment by BRAVO68WEB** [comment]
@Hyftar you should have come in issue before submitting an PR as this issue was assigned to @SerhatKayaa

**Comment by BRAVO68WEB** [comment]
Let me ask him if he would like to withdraw

**Comment by BRAVO68WEB** [comment]
@Hyftar Nice work 👍🏼 

If he withdraws then i will merge this PR

**Comment by BRAVO68WEB** [comment]
Actually those console.log("answers") were used to debug the code. To check where is it breaking, your should not have removed those

**Comment by Hyftar** [comment]
> 
> 
> Actually those console.log("answers") were used to debug the code. To check where is it breaking, your should not have removed those

It is a bad practice to keep commented code like this. You should use a proper debugger. That being said if it's really a problem I can put them back.

**Comment by BRAVO68WEB** [comment]
Ok sure

No problem
No need tp change now

**Comment by Hyftar** [comment]
@BRAVO68WEB if you don't mind, please add the `hacktoberfest-accepted` label to this PR so it counts towards my Hacktoberfest challenge progress even if you end up not merging the PR. Thanks!

**Comment by BRAVO68WEB** [comment]
Ok i will do it, but we have "hacktoberfest" topic in our repo

**Comment by Hyftar** [comment]
Yes of course, but starting this year to prevent spam, pull requests in repositories with the ‘hacktoberfest’ topic will also need to be merged, approved by a maintainer, or labeled as ‘hacktoberfest-accepted’ in order to qualify.

**Review by BRAVO68WEB — APPROVED** [review]

**Pull request merged**
